'use strict';

const errors = {
  SUCCESS: 0,
  INVALID_CERT_FORMAT: 1,
  INVALID_MAIL_SUBJECT: 2,
  INVALID_MAIL_TO: 3,
  INVALID_MAIL_FROM: 4,
  INVALID_MAIL_DATE: 5,
  INVALID_MAIL_CONTENTTYPE: 6,
  INVALID_MAIL_BODY: 7,
  INVALID_MAIL_DKIM: 8,
  UNKNOWN: 999
};

module.exports = errors;
